# SOPS Configuration - Friday 2.0
# Date: 2026-02-05
# Usage: Configuration pour chiffrement/déchiffrement des secrets avec age
#
# Setup requis:
# 1. Générer clé age: age-keygen -o ~/.age/friday-key.txt
# 2. Remplacer YOUR_AGE_PUBLIC_KEY ci-dessous par votre clé publique
# 3. Chiffrer: ./scripts/encrypt-env.sh
# 4. Déchiffrer: ./scripts/decrypt-env.sh
#
# ATTENTION: Ne JAMAIS utiliser "sops -d .env.enc" directement !
# L'extension .enc fait que SOPS assume du JSON et crash sur les commentaires #.
# Toujours utiliser les wrapper scripts ou ajouter les flags:
#   sops --input-type dotenv --output-type dotenv -d .env.enc
#
# Documentation complète: docs/secrets-management.md

creation_rules:
  # Fichiers .env (sources non chiffrées)
  - path_regex: \.env$
    age: age17zcpkgjxdyk6g34anhymukncq49dtf6k4f3vgp5fchsv04a8quzq7rjn8t  # Clé publique mainteneur

  # Fichiers .env.test (pour tests E2E)
  - path_regex: \.env\.(test|dec|decrypted)$
    age: age17zcpkgjxdyk6g34anhymukncq49dtf6k4f3vgp5fchsv04a8quzq7rjn8t  # Clé publique mainteneur

  # Fichiers .env chiffrés (pour édition in-place)
  - path_regex: \.env\.enc$
    age: age17zcpkgjxdyk6g34anhymukncq49dtf6k4f3vgp5fchsv04a8quzq7rjn8t  # Clé publique mainteneur

  # Fichiers .env.test.enc (tests E2E chiffrés)
  - path_regex: \.env\.test\.enc$
    age: age17zcpkgjxdyk6g34anhymukncq49dtf6k4f3vgp5fchsv04a8quzq7rjn8t  # Clé publique mainteneur

  # Fichiers .env.email (credentials 4 comptes IMAP)
  - path_regex: \.env\.email$
    age: age17zcpkgjxdyk6g34anhymukncq49dtf6k4f3vgp5fchsv04a8quzq7rjn8t  # Clé publique mainteneur

  # Fichiers .env.email.enc (credentials chiffrés)
  - path_regex: \.env\.email\.enc$
    age: age17zcpkgjxdyk6g34anhymukncq49dtf6k4f3vgp5fchsv04a8quzq7rjn8t  # Clé publique mainteneur

  # Fichiers secrets YAML/JSON
  - path_regex: secrets.*\.(yaml|json)$
    age: age17zcpkgjxdyk6g34anhymukncq49dtf6k4f3vgp5fchsv04a8quzq7rjn8t  # Clé publique mainteneur

  # Fichiers secrets YAML/JSON chiffrés
  - path_regex: secrets.*\.(yaml|json)\.enc$
    age: age17zcpkgjxdyk6g34anhymukncq49dtf6k4f3vgp5fchsv04a8quzq7rjn8t  # Clé publique mainteneur

# IMPORTANT:
# - Ce fichier PEUT être commité (contient seulement la clé publique)
# - La clé PRIVÉE (~/.age/friday-key.txt) ne doit JAMAIS être commitée
# - Pour partager avec un nouveau dev: ajouter sa clé publique ici (séparées par virgules)
#
# Exemple multi-dev:
#   age: >-
#     age1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq,
#     age1yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
